Repository les-projets-cagnottes/core, pull requests merged in 2022-05, with the labels that each got.

#335 feat(backlog#44): Permits the API to update several project statuses
  src/main/java/fr/lesprojetscagnottes/core/project/controller/ProjectController.java
  src/main/java/fr/lesprojetscagnottes/core/project/model/ProjectStatus.java
  src/main/java/fr/lesprojetscagnottes/core/project/service/ProjectService.java
Labels: size/M

#315 refactor: Implement some best practices around Organization and SlackTeam
  pom.xml
  src/main/java/fr/lesprojetscagnottes/core/organization/controller/OrganizationController.java
  src/main/java/fr/lesprojetscagnottes/core/organization/model/OrganizationModel.java
  src/main/java/fr/lesprojetscagnottes/core/organization/service/OrganizationService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/controller/SlackTeamController.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/model/SlackTeamModel.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/service/SlackTeamService.java
  src/test/java/fr/lesprojetscagnottes/core/steps/CampaignStepDefinitions.java
  src/test/java/fr/lesprojetscagnottes/core/steps/CommonStepDefinitions.java
  src/test/java/fr/lesprojetscagnottes/core/steps/ProjectStepDefinitions.java
Labels: size/L

#351 feat: Introducing Liquibase to versionize DB structure
  .github/workflows/build.yml
  .github/workflows/integration.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  README.md
  pom-cluecumber.xml
  pom.xml
  src/main/java/fr/lesprojetscagnottes/core/LPCCoreApplication.java
  src/main/java/fr/lesprojetscagnottes/core/idea/entity/IdeaEntity.java
  src/main/java/fr/lesprojetscagnottes/core/organization/controller/OrganizationController.java
  src/main/java/fr/lesprojetscagnottes/core/organization/model/OrganizationModel.java
  src/main/java/fr/lesprojetscagnottes/core/organization/service/OrganizationService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/controller/SlackTeamController.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/model/SlackTeamModel.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/service/SlackTeamService.java
  src/main/java/fr/lesprojetscagnottes/core/user/entity/UserEntity.java
  src/main/resources/application.properties
  src/main/resources/create.sql
  src/main/resources/db/changelog/db.changelog-0.13.sql
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/liquibase.properties
  src/test/java/fr/lesprojetscagnottes/core/RunCucumberTest.java
  src/test/java/fr/lesprojetscagnottes/core/steps/CampaignStepDefinitions.java
  src/test/java/fr/lesprojetscagnottes/core/steps/CommonStepDefinitions.java
  src/test/java/fr/lesprojetscagnottes/core/steps/ProjectStepDefinitions.java
  src/test/resources/application.properties
Labels: enhancement, size/XXL
