Repository les-projets-cagnottes/core, pull requests merged in 2023-03, with the labels that each got.

#457 Release 0.15.2
  pom-cluecumber.xml
  pom.xml
  src/main/java/fr/lesprojetscagnottes/core/LPCCoreApplication.java
  src/main/java/fr/lesprojetscagnottes/core/account/entity/AccountEntity.java
  src/main/java/fr/lesprojetscagnottes/core/authentication/controller/ApiTokenController.java
  src/main/java/fr/lesprojetscagnottes/core/budget/entity/BudgetEntity.java
  src/main/java/fr/lesprojetscagnottes/core/budget/service/BudgetService.java
  src/main/java/fr/lesprojetscagnottes/core/campaign/controller/CampaignController.java
  src/main/java/fr/lesprojetscagnottes/core/campaign/entity/CampaignEntity.java
  src/main/java/fr/lesprojetscagnottes/core/campaign/scheduler/CampaignScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/campaign/service/CampaignService.java
  src/main/java/fr/lesprojetscagnottes/core/common/date/DateUtils.java
  src/main/java/fr/lesprojetscagnottes/core/donation/controller/DonationController.java
  src/main/java/fr/lesprojetscagnottes/core/donation/entity/DonationEntity.java
  src/main/java/fr/lesprojetscagnottes/core/donation/model/DonationModel.java
  src/main/java/fr/lesprojetscagnottes/core/donation/queue/DonationOperation.java
  src/main/java/fr/lesprojetscagnottes/core/donation/repository/DonationRepository.java
  src/main/java/fr/lesprojetscagnottes/core/donation/service/DonationService.java
  src/main/java/fr/lesprojetscagnottes/core/donation/task/DonationProcessingTask.java
  src/main/java/fr/lesprojetscagnottes/core/notification/repository/NotificationRepository.java
  src/main/java/fr/lesprojetscagnottes/core/notification/service/NotificationService.java
  src/main/java/fr/lesprojetscagnottes/core/project/service/ProjectService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/microsoft/service/MicrosoftAuthenticationService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/SlackNotificationScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/controller/SlackController.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/service/SlackAuthenticationService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/task/CatcherTokenProviderTask.java
  src/main/java/fr/lesprojetscagnottes/core/user/controller/UserController.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-0.15.sql
  src/main/resources/demo/dataset.sql
  src/main/resources/templates/microsoft/fr/CAMPAIGN_REMINDER.txt
  src/main/resources/templates/microsoft/fr/CAMPAIGN_STARTED.txt
  src/main/resources/templates/slack/fr/CAMPAIGN_REMINDER.txt
  src/main/resources/templates/slack/fr/CAMPAIGN_STARTED.txt
  src/main/resources/templates/slack/fr/PROJECT_PUBLISHED.txt
  src/test/java/fr/lesprojetscagnottes/core/steps/DonationStepDefinitions.java
Labels: bug, size/XXL

#458 fix(backlog#10): implement notification to call projects for news
  pom-cluecumber.xml
  pom.xml
  src/main/java/fr/lesprojetscagnottes/core/campaign/scheduler/CampaignScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/news/controller/NewsController.java
  src/main/java/fr/lesprojetscagnottes/core/news/repository/NewsRepository.java
  src/main/java/fr/lesprojetscagnottes/core/news/service/NewsService.java
  src/main/java/fr/lesprojetscagnottes/core/notification/model/NotificationName.java
  src/main/java/fr/lesprojetscagnottes/core/project/model/ProjectModel.java
  src/main/java/fr/lesprojetscagnottes/core/project/repository/ProjectRepository.java
  src/main/java/fr/lesprojetscagnottes/core/project/scheduler/ProjectScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/project/service/ProjectService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/SlackNotificationScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/repository/SlackUserRepository.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/service/SlackUserService.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-0.16.sql
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/demo/dataset.sql
  src/main/resources/templates/slack/fr/PROJECT_CALL_FOR_NEWS.txt
Labels: size/L

#459 fix(backlog#10): implement notification to call projects for news
  pom-cluecumber.xml
  pom.xml
  src/main/java/fr/lesprojetscagnottes/core/campaign/scheduler/CampaignScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/news/controller/NewsController.java
  src/main/java/fr/lesprojetscagnottes/core/news/repository/NewsRepository.java
  src/main/java/fr/lesprojetscagnottes/core/news/service/NewsService.java
  src/main/java/fr/lesprojetscagnottes/core/notification/model/NotificationName.java
  src/main/java/fr/lesprojetscagnottes/core/project/model/ProjectModel.java
  src/main/java/fr/lesprojetscagnottes/core/project/repository/ProjectRepository.java
  src/main/java/fr/lesprojetscagnottes/core/project/scheduler/ProjectScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/project/service/ProjectService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/SlackNotificationScheduler.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/repository/SlackUserRepository.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/service/SlackUserService.java
  src/main/resources/application.properties
  src/main/resources/db/changelog/db.changelog-0.16.sql
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/demo/dataset.sql
  src/main/resources/templates/slack/fr/PROJECT_CALL_FOR_NEWS.txt
Labels: enhancement, size/L

#460 Release 0.16.1
  pom-cluecumber.xml
  pom.xml
  src/main/java/fr/lesprojetscagnottes/core/account/entity/AccountEntity.java
  src/main/java/fr/lesprojetscagnottes/core/budget/entity/BudgetEntity.java
  src/main/java/fr/lesprojetscagnottes/core/campaign/entity/CampaignEntity.java
  src/main/java/fr/lesprojetscagnottes/core/common/audit/AuditEntityListener.java
  src/main/java/fr/lesprojetscagnottes/core/content/entity/ContentEntity.java
  src/main/java/fr/lesprojetscagnottes/core/idea/entity/IdeaEntity.java
  src/main/java/fr/lesprojetscagnottes/core/news/entity/NewsEntity.java
  src/main/java/fr/lesprojetscagnottes/core/notification/entity/NotificationEntity.java
  src/main/java/fr/lesprojetscagnottes/core/organization/entity/OrganizationEntity.java
  src/main/java/fr/lesprojetscagnottes/core/project/entity/ProjectEntity.java
  src/main/java/fr/lesprojetscagnottes/core/providers/microsoft/entity/MicrosoftNotificationEntity.java
  src/main/java/fr/lesprojetscagnottes/core/providers/microsoft/entity/MicrosoftTeamEntity.java
  src/main/java/fr/lesprojetscagnottes/core/providers/microsoft/entity/MicrosoftUserEntity.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/entity/SlackNotificationEntity.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/entity/SlackTeamEntity.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/entity/SlackUserEntity.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/repository/SlackNotificationRepository.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/service/SlackNotificationService.java
  src/main/java/fr/lesprojetscagnottes/core/providers/slack/service/SlackTeamService.java
  src/main/java/fr/lesprojetscagnottes/core/user/entity/UserEntity.java
Labels: bug, size/L
